apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment
  labels:
    app: httpserver
spec:
  replicas: 2
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      imagePullSecrets:
        - name: cloudnative
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
        - name: httpserver
          image: cghua/httpserver:0.1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: httpport
              valueFrom:
                configMapKeyRef:
                  key: httpport
                  name: myenv
          ports:
            - containerPort: 8080
          # 资源需求和QoS
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 200m
              memory: 20Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /healthz
              httpHeaders:
                - name: Custom-Header
                  value: KevinChen
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 200
            failureThreshold: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30
  minReadySeconds: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: httpserver
spec:
  selector:
    app: httpserver
  ports:
    - port: 8080
      name: httpserver-port
      protocol: TCP
      targetPort: 8080
  type: ClusterIP