apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  generation: 1
  name: letsencrypt-prod
spec:
  acme:
    email: cghxxx@163.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencreypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01
          ingress:
            class: nginx