apiVersion: v1
items:
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    metadata:
      annotations:
        meta.helm.sh/release-name: kube-prometheus-stack
        meta.helm.sh/release-namespace: prometheus-stack
      creationTimestamp: "2022-03-11T05:47:59Z"
      generation: 2
      labels:
        app: kube-prometheus-stack-prometheus
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 33.2.0
        chart: kube-prometheus-stack-33.2.0
        heritage: Helm
        release: kube-prometheus-stack
      name: kube-prometheus-stack-prometheus
      namespace: prometheus-stack
      resourceVersion: "4059202"
      uid: d819465f-f360-4124-8eaa-97997ada65a5
    spec:
      additionalScrapeConfigs:
        key: prometheus-additional.yaml
        name: additional-configs
      alerting:
        alertmanagers:
        - apiVersion: v2
          name: kube-prometheus-stack-alertmanager
          namespace: prometheus-stack
          pathPrefix: /
          port: http-web
      enableAdminAPI: false
      externalUrl: http://kube-prometheus-stack-prometheus.prometheus-stack:9090
      image: quay.io/prometheus/prometheus:v2.33.4
      listenLocal: false
      logFormat: logfmt
      logLevel: info
      paused: false
      podMonitorNamespaceSelector: {}
      podMonitorSelector:
        matchLabels:
          release: kube-prometheus-stack
      portName: http-web
      probeNamespaceSelector: {}
      probeSelector:
        matchLabels:
          release: kube-prometheus-stack
      replicas: 1
      retention: 10d
      routePrefix: /
      ruleNamespaceSelector: {}
      ruleSelector:
        matchLabels:
          release: kube-prometheus-stack
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: kube-prometheus-stack-prometheus
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector:
        matchLabels:
          release: kube-prometheus-stack
      shards: 1
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 5Gi
            storageClassName: default
      version: v2.33.4
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""